from conexion.oracle_queries import OracleQueries

oracle = OracleQueries(can_write=True)
oracle.connect()

rarity_common_id = oracle.sqlToDataFrame("select id from labdatabase.\"rarity\" where \"tier\" = '1'")
rarity_uncommon_id = oracle.sqlToDataFrame("select id from labdatabase.\"rarity\" where \"tier\" = '2'")
rarity_rare_id = oracle.sqlToDataFrame("select id from labdatabase.\"rarity\" where \"tier\" = '3'")
rarity_epic_id = oracle.sqlToDataFrame("select id from labdatabase.\"rarity\" where \"tier\" = '4'")
rarity_legendary_id = oracle.sqlToDataFrame("select id from labdatabase.\"rarity\" where \"tier\" = '5'")

album_copa_id = oracle.sqlToDataFrame("select id from labdatabase.\"album\" where title = 'Copa do Mundo 2022'")
album_harrypotter_id = oracle.sqlToDataFrame("select id from labdatabase.\"album\" where title = 'Harry Potter'")
album_pokemon_id = oracle.sqlToDataFrame("select id from labdatabase.\"album\" where title = 'Pokemon'")

background_common_id = oracle.sqlToDataFrame("select id from labdatabase.\"background\" where rarity_id = '1'")
background_uncommon_id = oracle.sqlToDataFrame("select id from labdatabase.\"background\" where rarity_id = '2'")
background_rare_id = oracle.sqlToDataFrame("select id from labdatabase.\"background\" where rarity_id = '3'")
background_epic_id = oracle.sqlToDataFrame("select id from labdatabase.\"background\" where rarity_id = '4'")
background_legendary_id = oracle.sqlToDataFrame("select id from labdatabase.\"background\" where rarity_id = '5'")

border_common_id = oracle.sqlToDataFrame("select id from labdatabase.\"border\" where rarity_id = '1'")
border_uncommon_id = oracle.sqlToDataFrame("select id from labdatabase.\"border\" where rarity_id = '2'")
border_rare_id = oracle.sqlToDataFrame("select id from labdatabase.\"border\" where rarity_id = '3'")
border_epic_id = oracle.sqlToDataFrame("select id from labdatabase.\"border\" where rarity_id = '4'")
border_legendary_id = oracle.sqlToDataFrame("select id from labdatabase.\"border\" where rarity_id = '5'")

oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 4, 'mbappe.png', 'Kylian Mbappe', :1, :2, :3, :4)", [int(background_uncommon_id.iloc[0]["id"]), int(border_uncommon_id.iloc[0]["id"]), int(rarity_uncommon_id.iloc[0]["id"]), int(album_copa_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 5, 'ronaldinho.png', 'Ronaldinho Gaucho', :1, :2, :3, :4)", [int(background_legendary_id.iloc[0]["id"]), int(border_legendary_id.iloc[0]["id"]), int(rarity_legendary_id.iloc[0]["id"]), int(album_copa_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 6, 'ibrahimovic.png', 'Zlatan Ibrahimovic', :1, :2, :3, :4)", [int(background_epic_id.iloc[0]["id"]), int(border_epic_id.iloc[0]["id"]), int(rarity_epic_id.iloc[0]["id"]), int(album_copa_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 7, 'zidane.png', 'Zinédine Zidane', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_copa_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 8, 'kaka.png', 'Kaka', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_copa_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 9, 'pele.png', 'Pele', :1, :2, :3, :4)", [int(background_rare_id.iloc[0]["id"]), int(border_rare_id.iloc[0]["id"]), int(rarity_rare_id.iloc[0]["id"]), int(album_copa_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 10, 'maradona.png', 'Diego Maradona', :1, :2, :3, :4)", [int(background_uncommon_id.iloc[0]["id"]), int(border_uncommon_id.iloc[0]["id"]), int(rarity_uncommon_id.iloc[0]["id"]), int(album_copa_id.iloc[0]["id"])])

oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 4, 'squirtle.png', 'Squirtle', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_pokemon_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 5, 'pidgey.png', 'Pidgey', :1, :2, :3, :4)", [int(background_uncommon_id.iloc[0]["id"]), int(border_uncommon_id.iloc[0]["id"]), int(rarity_uncommon_id.iloc[0]["id"]), int(album_pokemon_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 6, 'psyduck.png', 'Psyduck', :1, :2, :3, :4)", [int(background_rare_id.iloc[0]["id"]), int(border_rare_id.iloc[0]["id"]), int(rarity_rare_id.iloc[0]["id"]), int(album_pokemon_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 7, 'onix.png', 'Onix', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_pokemon_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 8, 'eevee.png', 'Eevee', :1, :2, :3, :4)", [int(background_rare_id.iloc[0]["id"]), int(border_rare_id.iloc[0]["id"]), int(rarity_rare_id.iloc[0]["id"]), int(album_pokemon_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 9, 'dratini.png', 'Dratini', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_pokemon_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 10, 'articuno.png', 'Articuno', :1, :2, :3, :4)", [int(background_legendary_id.iloc[0]["id"]), int(border_legendary_id.iloc[0]["id"]), int(rarity_legendary_id.iloc[0]["id"]), int(album_pokemon_id.iloc[0]["id"])])

oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 4, 'hagrid.png', 'Rubeo Hagrid', :1, :2, :3, :4)", [int(background_uncommon_id.iloc[0]["id"]), int(border_uncommon_id.iloc[0]["id"]), int(rarity_uncommon_id.iloc[0]["id"]), int(album_harrypotter_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 5, 'dumbledore.png', 'Albus Dumbledore', :1, :2, :3, :4)", [int(background_legendary_id.iloc[0]["id"]), int(border_legendary_id.iloc[0]["id"]), int(rarity_legendary_id.iloc[0]["id"]), int(album_harrypotter_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 6, 'voldemort.png', 'Lord Voldemort', :1, :2, :3, :4)", [int(background_epic_id.iloc[0]["id"]), int(border_epic_id.iloc[0]["id"]), int(rarity_epic_id.iloc[0]["id"]), int(album_harrypotter_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 7, 'snape.png', 'Severus Snape', :1, :2, :3, :4)", [int(background_rare_id.iloc[0]["id"]), int(border_rare_id.iloc[0]["id"]), int(rarity_rare_id.iloc[0]["id"]), int(album_harrypotter_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 8, 'bellatrix.png', 'Bellatrix Lestrange', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_harrypotter_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 9, 'dobby.png', 'Dobby', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_harrypotter_id.iloc[0]["id"])])
oracle.write("insert into \"card\" (id, \"number\", \"image\", \"name\", background_id, border_id, rarity_id, album_id) values(card_id_seq.NEXTVAL, 10, 'sirius.png', 'Sirius Black', :1, :2, :3, :4)", [int(background_common_id.iloc[0]["id"]), int(border_common_id.iloc[0]["id"]), int(rarity_common_id.iloc[0]["id"]), int(album_harrypotter_id.iloc[0]["id"])])

attacker_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Attacker'")
mid_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Mid'")
water_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Water'")
grass_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Grass'")
fire_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Fire'")
electric_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Electric'")
poison_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Poison'")
flying_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Flying'")
normal_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Normal'")
dragon_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Dragon'")
ice_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Ice'")
stone_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Stone'")
wizard_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Wizard'")
elf_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Elf'")
death_eaters_tag_id = oracle.sqlToDataFrame("select id from labdatabase.\"tag\" where \"name\" = 'Death Eaters'")

oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Neymar Junior'").iloc[0]["id"]), int(attacker_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Lionel Messi'").iloc[0]["id"]), int(attacker_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Cristiano Ronaldo'").iloc[0]["id"]), int(attacker_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Kylian Mbappe'").iloc[0]["id"]), int(attacker_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Zlatan Ibrahimovic'").iloc[0]["id"]), int(attacker_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Pele'").iloc[0]["id"]), int(attacker_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Diego Maradona'").iloc[0]["id"]), int(mid_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Ronaldinho Gaucho'").iloc[0]["id"]), int(mid_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Zinédine Zidane'").iloc[0]["id"]), int(mid_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Kaka'").iloc[0]["id"]), int(mid_tag_id.iloc[0]["id"])])


oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Squirtle'").iloc[0]["id"]), int(water_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Psyduck'").iloc[0]["id"]), int(water_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Eevee'").iloc[0]["id"]), int(normal_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Pidgey'").iloc[0]["id"]), int(normal_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Articuno'").iloc[0]["id"]), int(flying_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Articuno'").iloc[0]["id"]), int(ice_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Dratini'").iloc[0]["id"]), int(ice_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Dratini'").iloc[0]["id"]), int(dragon_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Bulbasaur'").iloc[0]["id"]), int(grass_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Bulbasaur'").iloc[0]["id"]), int(poison_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Charmander'").iloc[0]["id"]), int(fire_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Pikachu'").iloc[0]["id"]), int(electric_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Onix'").iloc[0]["id"]), int(stone_tag_id.iloc[0]["id"])])


oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Harry Potter'").iloc[0]["id"]), int(wizard_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Rony Weasley'").iloc[0]["id"]), int(wizard_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Hermione Granger'").iloc[0]["id"]), int(wizard_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Rubeo Hagrid'").iloc[0]["id"]), int(wizard_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Albus Dumbledore'").iloc[0]["id"]), int(wizard_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Severus Snape'").iloc[0]["id"]), int(wizard_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Sirius Black'").iloc[0]["id"]), int(wizard_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Dobby'").iloc[0]["id"]), int(elf_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Lord Voldemort'").iloc[0]["id"]), int(death_eaters_tag_id.iloc[0]["id"])])
oracle.write("insert into \"card_tag\" (card_id, tag_id) values(:1, :2)", [int(oracle.sqlToDataFrame("select id from labdatabase.\"card\" where \"name\" = 'Bellatrix Lestrange'").iloc[0]["id"]), int(death_eaters_tag_id.iloc[0]["id"])])

